version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root_password  # change to a secure password
      MYSQL_DATABASE: my_database        # change to your database name
      MYSQL_USER: my_user                # change to your database user
      MYSQL_PASSWORD: my_password        # change to your user password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
    driver: local