version: "3.8"

services:
  app:
    image: theoguzhan/web-engineering-project:latest
    ports:
      - "8080:8080"
      - "3000:3000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=mariadb
      - DB_USER=mariadb
      - DB_PASSWORD=mariadb
    depends_on:
      - db
    networks:
      - webengineering-network
    restart: unless-stopped

  db:
    image: mariadb:10.4
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: mariadb
      MYSQL_DATABASE: mariadb
      MYSQL_USER: mariadb
      MYSQL_PASSWORD: mariadb
    ports:
      - "3306:3306"
    volumes:
      - mariadb-data:/var/lib/mysql
    networks:
      - webengineering-network

volumes:
  mariadb-data:

networks:
  webengineering-network:
    driver: bridge
